// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServisTakipWebAPI.Models;

#nullable disable

namespace ServisTakipWebAPI.Migrations
{
    [DbContext(typeof(ServisTakipDbContext))]
    [Migration("20240201095002_migg_add_productmovements")]
    partial class migg_add_productmovements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServisTakipWebAPI.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("CustomerCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ServisTakipWebAPI.Models.FaultTrack", b =>
                {
                    b.Property<int>("FaultTrackingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaultTrackingID"));

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EstimatedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FaultCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaultDefinition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaultDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaultDocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FaultStage")
                        .HasColumnType("int");

                    b.Property<DateTime>("FaultUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaultWorkerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("FaultTrackingID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProductID");

                    b.ToTable("FaultTracks");
                });

            modelBuilder.Entity("ServisTakipWebAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("ProductAccessories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductSerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("ProductType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ServisTakipWebAPI.Models.ProductMovement", b =>
                {
                    b.Property<int>("MovementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovementID"));

                    b.Property<int?>("FaultTrackingID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovementDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovementID");

                    b.HasIndex("FaultTrackingID");

                    b.ToTable("ProductMovements");
                });

            modelBuilder.Entity("ServisTakipWebAPI.Models.FaultTrack", b =>
                {
                    b.HasOne("ServisTakipWebAPI.Models.Customer", "Customer")
                        .WithMany("FaultTrack")
                        .HasForeignKey("CustomerID");

                    b.HasOne("ServisTakipWebAPI.Models.Product", "Product")
                        .WithMany("FaultTrack")
                        .HasForeignKey("ProductID");

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ServisTakipWebAPI.Models.ProductMovement", b =>
                {
                    b.HasOne("ServisTakipWebAPI.Models.FaultTrack", "FaultTrack")
                        .WithMany("ProductMovements")
                        .HasForeignKey("FaultTrackingID");

                    b.Navigation("FaultTrack");
                });

            modelBuilder.Entity("ServisTakipWebAPI.Models.Customer", b =>
                {
                    b.Navigation("FaultTrack");
                });

            modelBuilder.Entity("ServisTakipWebAPI.Models.FaultTrack", b =>
                {
                    b.Navigation("ProductMovements");
                });

            modelBuilder.Entity("ServisTakipWebAPI.Models.Product", b =>
                {
                    b.Navigation("FaultTrack");
                });
#pragma warning restore 612, 618
        }
    }
}
